samples: samples.csv

star_index: /home/groups/carilee/refs/rnaseq-refs/hg38/star_index
star_threads: 4
star_container: https://depot.galaxyproject.org/singularity/star%3A2.7.9a--h9ee0642_0

rsem_ref: /home/groups/carilee/refs/rnaseq-refs/hg38/rsem_ref
rsem_threads: 4
rsem_container: https://depot.galaxyproject.org/singularity/rsem%3A1.3.3--pl5262h3198e80_2

